### ISSUE TITLE
[devbuild] Non-existing asset images not replaced by dummies @ Pokemon Hider

### ISSUE THREAD

**Issue by darkelement1987** [SenorKarlos/RocketMap#119]
No dummies are loaded when image is missing from the assets:

These are not in assets, there should be dummies here (pokemon_icon_000.png)
![image](https://user-images.githubusercontent.com/21128187/38695517-caf5eafe-3e8c-11e8-84af-0a2c0eaa765e.png)

Working fine for others:
![image](https://user-images.githubusercontent.com/21128187/38695521-ce6a8f50-3e8c-11e8-9ce0-cc2c19c0a04f.png)

i think it's in these lines of dyn_img.py but not sure:

 ```py
from pgoapi.protos.pogoprotos.enums.costume_pb2 import Costume
from pgoapi.protos.pogoprotos.enums.form_pb2 import Form
from pgoapi.protos.pogoprotos.enums.gender_pb2 import (
    MALE, FEMALE, Gender, GENDERLESS, GENDER_UNSET)
from pgoapi.protos.pogoprotos.enums.weather_condition_pb2 import (
    WeatherCondition, CLEAR, RAINY,
    PARTLY_CLOUDY, OVERCAST, WINDY, SNOW, FOG)
```

It used to `import *` before Travis.

Worked fine on `MIX_MEWTWO`

**Comment by rlodev67** [comment]
Fixed in https://github.com/SenorKarlos/RocketMap/commit/8e14cf9e0390f65adb967651f267ee5ba39696a8
