### ISSUE TITLE
notify of perfection not saved

### ISSUE THREAD

**Issue by brianprak** [SenorKarlos/RocketMap#39]
![imagefilled](https://user-images.githubusercontent.com/23522451/35972362-d390480e-0cd1-11e8-82e0-77a38914ad90.jpg)
![imageempty](https://user-images.githubusercontent.com/23522451/35972363-d3a91758-0cd1-11e8-855d-646b4268046a.jpg)

## Expected Behavior
When i set notify of perfection to 95 and toggle the slide hide unnotified i like to see all pokemon with at least 95% iv.

## Current Behavior
When i set notify of perfection to 95 and toggle the slide hide unnotified the page refreshes but the notify of perfection box is empty.
The same thing occures on notify on specific pokemon.

## Possible Solution
Keep the setting.

## Steps to Reproduce (for bugs)
1. set notify perfection to 95
2. toggle the hide unnotified slide
3. page refreshes automatic but now the notify perfection is empty

**Comment by whitewillem** [comment]
Looks like stock RM has the same problem. 

[https://github.com/RocketMap/RocketMap/issues/2483](url)

**Comment by rlodev67** [comment]
Does someone have more information ? Like JS console output ?

**Comment by rlodev67** [comment]
Fix is coming

**Comment by brianprak** [comment]
Fixed with latest release
