### ISSUE TITLE
Notify by level is broken!

### ISSUE THREAD

**Issue by darkelement1987** [SenorKarlos/RocketMap#42]
**Problem:**

Whenever you enter a level to notify you, all Pokémon disappear from the map. Filter doesn't seem to work at all.

Works fine for perfection notifications

**Tested with:**

Pokemon ranging from 0-39 were on my map
On latest git build
Tested on different maps, browsers and devices

**Steps to reproduce:**

1. Notify by level 20 (or other low number)
2. Click 'Hide unnotified'
3. Result:  no more pokemon on map

**Comment by Deewii** [comment]
Easily fixed, seems to be a small "typo" in the code.

``function isNotifyPerfectionPoke(poke) {

    var hasHighIV = false
    var hasHighLevel = false
    var hasHighAttributes = false

    if (poke['individual_attack'] != null && poke['cp_multiplier'] !== null) {
        const perfection = getIv(poke['individual_attack'], poke['individual_defense'], poke['individual_stamina'])
        const level = getPokemonLevel(poke['cp_multiplier'])

        hasHighIV = notifiedMinPerfection > 0 && perfection >= notifiedMinPerfection
        hasHighLevel = notifiedMinLevel > 0 && level >= notifiedMinLevel

        hasHighAttributes = (hasHighIV && !(notifiedMinLevel > 0)) || (hasHighLevel && !(notifiedMinPerfection > 0)) || hasHighLevel && hasHighIV
    }

    return hasHighIV
}``

should return ``return hasHighAttributes``

**Comment by darkelement1987** [comment]
> function isNotifyPerfectionPoke(poke) {

    var hasHighIV = false
    var hasHighLevel = false
    var hasHighAttributes = false

    if (poke['individual_attack'] != null && poke['cp_multiplier'] !== null) {
        const perfection = getIv(poke['individual_attack'], poke['individual_defense'], poke['individual_stamina'])
        const level = getPokemonLevel(poke['cp_multiplier'])

        hasHighIV = notifiedMinPerfection > 0 && perfection >= notifiedMinPerfection
        hasHighLevel = notifiedMinLevel > 0 && level >= notifiedMinLevel

        hasHighAttributes = (hasHighIV && !(notifiedMinLevel > 0)) || (hasHighLevel && !(notifiedMinPerfection > 0)) || hasHighLevel && hasHighIV
    }

    return hasHighIV
}

This is the right code or is this a part that still needs replacement?

**Comment by darkelement1987** [comment]
Question, stock rm uses `    return isOnNotifyList || hasHighIV` why is this different?

**Comment by rlodev67** [comment]
@darkelement1987 Cause Pokemon on notify list shouldn't be hide
