### ISSUE TITLE
Gender is incorrect for caught pokemon. 

### ISSUE THREAD

**Issue by dpegasusm** [SenorKarlos/RocketMap#54]
Gender is using the get map objects call to display the gender info. Currently the game has a bug where the gender of the pokemon as displayed on the map will not always match the gender of the encountered pokemon. This can be seen easily with pokemon that have obvious gender differences like magikarp with its whiskers and pikachu with its tail. The pokemon may display as male on the map but once clicked it will be female or vice versa. The same gender is still used for all trainer levels. The only way to completely guarantee gender is to use the gender from the encounter data on IV checked pokemon instead of getting the gender when the get map objects is called to display the mons shown on the map.

## Expected Behavior
Gender of pokemon caught matches gender shown on map.

## Current Behavior
Gender does not always match map gender indicated. 

## Possible Solution
Instead of using the get map objects call to display a pokemon's gender use the gender from the encounter data from IV checked mons. 

## Steps to Reproduce (for bugs)
catch pokemon and cross reference gender with gender indicated.

**Comment by rlodev67** [comment]
Yes, it's since a niantic update
Could you make the PR ?

**Comment by tomballgithub** [comment]
Fixed #61
